defmodule Algoie.Repo.TenantMigrations.AddMediaAssets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:media_assets, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :store_id,
          references(:stores,
            column: :id,
            name: "media_assets_store_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :url, :text, null: false
      add :filename, :text, null: false
      add :content_type, :text
      add :size, :bigint
      add :width, :bigint
      add :height, :bigint
      add :alt_text, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:media_assets, "media_assets_store_id_fkey")

    drop table(:media_assets, prefix: prefix())
  end
end
