defmodule Algoie.Repo.TenantMigrations.CustomerEmailCaseInsensitive do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers, prefix: prefix()) do
      modify :email, :citext
    end
  end

  def down do
    alter table(:customers, prefix: prefix()) do
      modify :email, :text
    end
  end
end
