defmodule Algoie.Repo.TenantMigrations.CustomerAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers, prefix: prefix()) do
      add :hashed_password, :text
    end
  end

  def down do
    alter table(:customers, prefix: prefix()) do
      remove :hashed_password
    end
  end
end
