defmodule Algoie.Repo.TenantMigrations.BrandCategorySeo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:categories, prefix: prefix()) do
      add :slug, :text
      add :description, :text
      add :image_url, :text
      add :meta_title, :text
      add :meta_description, :text
    end

    alter table(:brands, prefix: prefix()) do
      add :slug, :text
      add :description, :text
      add :image_url, :text
      add :meta_title, :text
      add :meta_description, :text
    end

    flush()

    execute("""
    UPDATE "#{prefix()}".categories
    SET slug = trim(both '-' from regexp_replace(lower(name), '[^a-z0-9]+', '-', 'g')) || '-' || substring(id::text, 1, 6)
    WHERE slug IS NULL
    """)

    execute("""
    UPDATE "#{prefix()}".brands
    SET slug = trim(both '-' from regexp_replace(lower(name), '[^a-z0-9]+', '-', 'g')) || '-' || substring(id::text, 1, 6)
    WHERE slug IS NULL
    """)

    alter table(:categories, prefix: prefix()) do
      modify :slug, :text, null: false
    end

    alter table(:brands, prefix: prefix()) do
      modify :slug, :text, null: false
    end

    create unique_index(:categories, [:store_id, :slug],
             name: "categories_unique_category_slug_index"
           )

    create unique_index(:brands, [:store_id, :slug], name: "brands_unique_brand_slug_index")
  end

  def down do
    drop_if_exists unique_index(:brands, [:store_id, :slug],
                     name: "brands_unique_brand_slug_index"
                   )

    alter table(:brands, prefix: prefix()) do
      remove :meta_description
      remove :meta_title
      remove :image_url
      remove :description
      remove :slug
    end

    drop_if_exists unique_index(:categories, [:store_id, :slug],
                     name: "categories_unique_category_slug_index"
                   )

    alter table(:categories, prefix: prefix()) do
      remove :meta_description
      remove :meta_title
      remove :image_url
      remove :description
      remove :slug
    end
  end
end
