defmodule Algoie.Repo.TenantMigrations.Day2Commerce do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:variants, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :product_id, :uuid, null: false
      add :store_id, :uuid, null: false
      add :sku, :text, null: false
      add :price, :decimal, null: false, precision: 18, scale: 2
      add :compare_at_price, :decimal, precision: 18, scale: 2
      add :stock, :bigint, null: false, default: 0
      add :track_inventory?, :boolean, null: false, default: true
      add :option_values, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:variants, [:store_id, :sku], name: "variants_unique_sku_index")

    alter table(:users, prefix: prefix()) do
      modify :name, :text, null: true
    end

    create table(:products, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:variants, prefix: prefix()) do
      modify :product_id,
             references(:products,
               column: :id,
               name: "variants_product_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :store_id,
             references(:stores,
               column: :id,
               name: "variants_store_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:products, prefix: prefix()) do
      add :name, :text, null: false
      add :description, :text

      add :store_id,
          references(:stores,
            column: :id,
            name: "products_store_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :brand_id, :uuid
      add :category_id, :uuid
      add :status, :text, null: false, default: "draft"
      add :images, {:array, :text}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:orders, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :store_id,
          references(:stores,
            column: :id,
            name: "orders_store_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :customer_id, :uuid, null: false
      add :coupon_id, :uuid
      add :status, :text, null: false, default: "pending"
      add :total_amount, :decimal, null: false, default: "0", precision: 18, scale: 2

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:order_line_items, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :order_id,
          references(:orders,
            column: :id,
            name: "order_line_items_order_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :variant_id,
          references(:variants,
            column: :id,
            name: "order_line_items_variant_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :quantity, :bigint, null: false
      add :unit_price, :decimal, null: false, precision: 18, scale: 2

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:customers, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders, prefix: prefix()) do
      modify :customer_id,
             references(:customers,
               column: :id,
               name: "orders_customer_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:customers, prefix: prefix()) do
      add :name, :text, null: false
      add :email, :text
      add :phone, :text

      add :store_id,
          references(:stores,
            column: :id,
            name: "customers_store_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:customers, [:store_id, :email],
             name: "customers_unique_customer_email_index"
           )

    create table(:coupons, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders, prefix: prefix()) do
      modify :coupon_id,
             references(:coupons,
               column: :id,
               name: "orders_coupon_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:coupons, prefix: prefix()) do
      add :code, :text, null: false
      add :discount_type, :text, null: false
      add :discount_value, :decimal, null: false, precision: 18, scale: 2
      add :min_order_value, :decimal, precision: 18, scale: 2
      add :starts_at, :utc_datetime
      add :expires_at, :utc_datetime
      add :usage_limit, :bigint
      add :times_used, :bigint, null: false, default: 0

      add :store_id,
          references(:stores,
            column: :id,
            name: "coupons_store_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:coupons, [:store_id, :code], name: "coupons_unique_coupon_code_index")

    create table(:collections, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text

      add :store_id,
          references(:stores,
            column: :id,
            name: "collections_store_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:collection_products, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :collection_id,
          references(:collections,
            column: :id,
            name: "collection_products_collection_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :product_id,
          references(:products,
            column: :id,
            name: "collection_products_product_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:collection_products, [:collection_id, :product_id],
             name: "collection_products_unique_collection_product_index"
           )

    create table(:categories, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :store_id,
          references(:stores,
            column: :id,
            name: "categories_store_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :parent_id,
          references(:categories,
            column: :id,
            name: "categories_parent_id_fkey",
            type: :uuid,
            prefix: prefix()
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:brands, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:products, prefix: prefix()) do
      modify :brand_id,
             references(:brands,
               column: :id,
               name: "products_brand_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :category_id,
             references(:categories,
               column: :id,
               name: "products_category_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:brands, prefix: prefix()) do
      add :name, :text, null: false

      add :store_id,
          references(:stores,
            column: :id,
            name: "brands_store_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:brands, "brands_store_id_fkey")

    alter table(:brands, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :store_id
      remove :name
    end

    drop constraint(:products, "products_brand_id_fkey")

    drop constraint(:products, "products_category_id_fkey")

    alter table(:products, prefix: prefix()) do
      modify :category_id, :uuid
      modify :brand_id, :uuid
    end

    drop table(:brands, prefix: prefix())

    drop constraint(:categories, "categories_store_id_fkey")

    drop constraint(:categories, "categories_parent_id_fkey")

    drop table(:categories, prefix: prefix())

    drop constraint(:collection_products, "collection_products_collection_id_fkey")

    drop constraint(:collection_products, "collection_products_product_id_fkey")

    drop_if_exists unique_index(:collection_products, [:collection_id, :product_id],
                     name: "collection_products_unique_collection_product_index"
                   )

    drop table(:collection_products, prefix: prefix())

    drop constraint(:collections, "collections_store_id_fkey")

    drop table(:collections, prefix: prefix())

    drop constraint(:coupons, "coupons_store_id_fkey")

    drop_if_exists unique_index(:coupons, [:store_id, :code],
                     name: "coupons_unique_coupon_code_index"
                   )

    alter table(:coupons, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :store_id
      remove :times_used
      remove :usage_limit
      remove :expires_at
      remove :starts_at
      remove :min_order_value
      remove :discount_value
      remove :discount_type
      remove :code
    end

    drop constraint(:orders, "orders_coupon_id_fkey")

    alter table(:orders, prefix: prefix()) do
      modify :coupon_id, :uuid
    end

    drop table(:coupons, prefix: prefix())

    drop constraint(:customers, "customers_store_id_fkey")

    drop_if_exists unique_index(:customers, [:store_id, :email],
                     name: "customers_unique_customer_email_index"
                   )

    alter table(:customers, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :store_id
      remove :phone
      remove :email
      remove :name
    end

    drop constraint(:orders, "orders_customer_id_fkey")

    alter table(:orders, prefix: prefix()) do
      modify :customer_id, :uuid
    end

    drop table(:customers, prefix: prefix())

    drop constraint(:order_line_items, "order_line_items_order_id_fkey")

    drop constraint(:order_line_items, "order_line_items_variant_id_fkey")

    drop table(:order_line_items, prefix: prefix())

    drop constraint(:orders, "orders_store_id_fkey")

    drop table(:orders, prefix: prefix())

    drop constraint(:products, "products_store_id_fkey")

    alter table(:products, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :images
      remove :status
      remove :category_id
      remove :brand_id
      remove :store_id
      remove :description
      remove :name
    end

    drop constraint(:variants, "variants_product_id_fkey")

    drop constraint(:variants, "variants_store_id_fkey")

    alter table(:variants, prefix: prefix()) do
      modify :store_id, :uuid
      modify :product_id, :uuid
    end

    drop table(:products, prefix: prefix())

    alter table(:users, prefix: prefix()) do
      modify :name, :text, null: false
    end

    drop_if_exists unique_index(:variants, [:store_id, :sku], name: "variants_unique_sku_index")

    drop table(:variants, prefix: prefix())
  end
end
