defmodule Algoie.Repo.TenantMigrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
      add :name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:stores, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :custom_domain, :text
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:stores, [:slug], name: "stores_unique_slug_index")

    create table(:store_staff, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "store_staff_user_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :store_id,
          references(:stores,
            column: :id,
            name: "store_staff_store_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false
    end

    create unique_index(:store_staff, [:user_id, :store_id],
             name: "store_staff_unique_user_store_index"
           )
  end

  def down do
    drop constraint(:store_staff, "store_staff_user_id_fkey")

    drop constraint(:store_staff, "store_staff_store_id_fkey")

    drop_if_exists unique_index(:store_staff, [:user_id, :store_id],
                     name: "store_staff_unique_user_store_index"
                   )

    drop table(:store_staff, prefix: prefix())

    drop_if_exists unique_index(:stores, [:slug], name: "stores_unique_slug_index")

    drop table(:stores, prefix: prefix())

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users, prefix: prefix())
  end
end
