defmodule Algoie.Repo.TenantMigrations.InventoryDeliveryStoreSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stores, prefix: prefix()) do
      add :email, :text
      add :phone, :text
      add :address, :text
      add :city, :text
      add :country, :text, null: false, default: "Bangladesh"
      add :currency, :text, null: false, default: "BDT"
      add :logo_url, :text
      add :invoice_prefix, :text, null: false, default: "INV"
    end

    alter table(:orders, prefix: prefix()) do
      add :delivery_charge_id, :uuid
      add :delivery_method, :text
    end

    create table(:delivery_charges, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders, prefix: prefix()) do
      modify :delivery_charge_id,
             references(:delivery_charges,
               column: :id,
               name: "orders_delivery_charge_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:delivery_charges, prefix: prefix()) do
      add :store_id,
          references(:stores,
            column: :id,
            name: "delivery_charges_store_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :name, :text, null: false
      add :city, :text
      add :area, :text
      add :charge, :decimal, null: false, precision: 18, scale: 2
      add :free_delivery_threshold, :decimal, precision: 18, scale: 2
      add :estimated_days_min, :bigint, null: false, default: 1
      add :estimated_days_max, :bigint, null: false, default: 3
      add :priority, :bigint, null: false, default: 0
      add :active?, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:delivery_charges, [:store_id, :name],
             name: "delivery_charges_unique_delivery_charge_name_index"
           )
  end

  def down do
    drop constraint(:delivery_charges, "delivery_charges_store_id_fkey")

    drop_if_exists unique_index(:delivery_charges, [:store_id, :name],
                     name: "delivery_charges_unique_delivery_charge_name_index"
                   )

    alter table(:delivery_charges, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :active?
      remove :priority
      remove :estimated_days_max
      remove :estimated_days_min
      remove :free_delivery_threshold
      remove :charge
      remove :area
      remove :city
      remove :name
      remove :store_id
    end

    drop constraint(:orders, "orders_delivery_charge_id_fkey")

    alter table(:orders, prefix: prefix()) do
      modify :delivery_charge_id, :uuid
    end

    drop table(:delivery_charges, prefix: prefix())

    alter table(:orders, prefix: prefix()) do
      remove :delivery_method
      remove :delivery_charge_id
    end

    alter table(:stores, prefix: prefix()) do
      remove :invoice_prefix
      remove :logo_url
      remove :currency
      remove :country
      remove :city
      remove :address
      remove :phone
      remove :email
    end
  end
end
