defmodule Algoie.Repo.TenantMigrations.OrderCustomersCoupons do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders, prefix: prefix()) do
      add :order_number, :text
      add :subtotal_amount, :decimal, null: false, default: "0", precision: 18, scale: 2
      add :discount_amount, :decimal, null: false, default: "0", precision: 18, scale: 2
      add :shipping_amount, :decimal, null: false, default: "0", precision: 18, scale: 2
      add :coupon_code, :text
      add :customer_name, :text
      add :customer_email, :text
      add :customer_phone, :text
      add :shipping_address, :map
      add :notes, :text
      add :payment_status, :text, null: false, default: "pending"
      add :fulfillment_status, :text, null: false, default: "unfulfilled"
      add :courier_provider, :text
      add :courier_consignment_id, :text
      add :tracking_code, :text
      add :courier_payload, :map, default: %{}
    end

    create unique_index(:orders, [:store_id, :order_number],
             name: "orders_unique_order_number_index"
           )

    alter table(:order_line_items, prefix: prefix()) do
      add :product_name, :text
      add :variant_name, :text
      add :sku, :text
    end

    create table(:customer_addresses, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :customer_id,
          references(:customers,
            column: :id,
            name: "customer_addresses_customer_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :store_id,
          references(:stores,
            column: :id,
            name: "customer_addresses_store_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :label, :text, default: "Delivery address"
      add :recipient_name, :text, null: false
      add :phone, :text, null: false
      add :address_line1, :text, null: false
      add :address_line2, :text
      add :city, :text, null: false
      add :area, :text
      add :postal_code, :text
      add :country, :text, null: false, default: "Bangladesh"
      add :default?, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:coupons, prefix: prefix()) do
      add :active?, :boolean, null: false, default: true
    end

    flush()

    execute("""
    UPDATE "#{prefix()}".orders AS orders
    SET order_number = 'LEGACY-' || upper(substring(orders.id::text, 1, 8)),
        customer_name = customers.name,
        customer_email = customers.email,
        customer_phone = customers.phone,
        shipping_address = '{}'::jsonb,
        subtotal_amount = orders.total_amount
    FROM "#{prefix()}".customers AS customers
    WHERE customers.id = orders.customer_id AND orders.order_number IS NULL
    """)

    execute("""
    UPDATE "#{prefix()}".order_line_items AS items
    SET product_name = products.name,
        sku = variants.sku
    FROM "#{prefix()}".variants AS variants
    JOIN "#{prefix()}".products AS products ON products.id = variants.product_id
    WHERE variants.id = items.variant_id AND items.product_name IS NULL
    """)

    alter table(:orders, prefix: prefix()) do
      modify :order_number, :text, null: false
      modify :customer_name, :text, null: false
      modify :shipping_address, :map, null: false
    end

    alter table(:order_line_items, prefix: prefix()) do
      modify :product_name, :text, null: false
      modify :sku, :text, null: false
    end
  end

  def down do
    alter table(:coupons, prefix: prefix()) do
      remove :active?
    end

    drop constraint(:customer_addresses, "customer_addresses_customer_id_fkey")

    drop constraint(:customer_addresses, "customer_addresses_store_id_fkey")

    drop table(:customer_addresses, prefix: prefix())

    alter table(:order_line_items, prefix: prefix()) do
      remove :sku
      remove :variant_name
      remove :product_name
    end

    drop_if_exists unique_index(:orders, [:store_id, :order_number],
                     name: "orders_unique_order_number_index"
                   )

    alter table(:orders, prefix: prefix()) do
      remove :courier_payload
      remove :tracking_code
      remove :courier_consignment_id
      remove :courier_provider
      remove :fulfillment_status
      remove :payment_status
      remove :notes
      remove :shipping_address
      remove :customer_phone
      remove :customer_email
      remove :customer_name
      remove :coupon_code
      remove :shipping_amount
      remove :discount_amount
      remove :subtotal_amount
      remove :order_number
    end
  end
end
