defmodule Algoie.Repo.TenantMigrations.EnhanceProductManagement do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:variants, prefix: prefix()) do
      add :cost_price, :decimal, precision: 18, scale: 2
      add :barcode, :text
      add :reserved_quantity, :bigint, null: false, default: 0
      add :low_stock_threshold, :bigint, null: false, default: 10
      add :position, :bigint, null: false, default: 0
    end

    create table(:tags, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false

      add :store_id,
          references(:stores,
            column: :id,
            name: "tags_store_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tags, [:store_id, :slug], name: "tags_unique_slug_index")

    drop_if_exists constraint(:store_staff, "store_staff_store_id_fkey")

    drop_if_exists constraint(:store_staff, "store_staff_user_id_fkey")

    alter table(:store_staff, prefix: prefix()) do
      modify :store_id, :uuid
      modify :user_id, :uuid
    end

    create index(:store_staff, [:user_id])

    create index(:store_staff, [:store_id])

    alter table(:products, prefix: prefix()) do
      remove :images
      add :slug, :text
      add :product_type, :text, null: false, default: "simple"
      add :featured, :boolean, null: false, default: false
      add :is_new, :boolean, null: false, default: false
      add :attribute_definitions, :map, default: %{}
      add :meta_title, :text
      add :meta_description, :text
    end

    create unique_index(:products, [:store_id, :slug], name: "products_unique_slug_index")

    create table(:product_tags, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :product_id,
          references(:products,
            column: :id,
            name: "product_tags_product_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "product_tags_tag_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:product_tags, [:product_id, :tag_id],
             name: "product_tags_unique_product_tag_index"
           )

    create table(:product_images, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :product_id,
          references(:products,
            column: :id,
            name: "product_images_product_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :variant_id,
          references(:variants,
            column: :id,
            name: "product_images_variant_id_fkey",
            type: :uuid,
            prefix: prefix()
          )

      add :media_asset_id,
          references(:media_assets,
            column: :id,
            name: "product_images_media_asset_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :alt_text, :text
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:product_images, "product_images_product_id_fkey")

    drop constraint(:product_images, "product_images_variant_id_fkey")

    drop constraint(:product_images, "product_images_media_asset_id_fkey")

    drop table(:product_images, prefix: prefix())

    drop constraint(:product_tags, "product_tags_product_id_fkey")

    drop constraint(:product_tags, "product_tags_tag_id_fkey")

    drop_if_exists unique_index(:product_tags, [:product_id, :tag_id],
                     name: "product_tags_unique_product_tag_index"
                   )

    drop table(:product_tags, prefix: prefix())

    drop_if_exists unique_index(:products, [:store_id, :slug], name: "products_unique_slug_index")

    alter table(:products, prefix: prefix()) do
      remove :meta_description
      remove :meta_title
      remove :attribute_definitions
      remove :is_new
      remove :featured
      remove :product_type
      remove :slug
      add :images, {:array, :text}, default: []
    end

    drop_if_exists index(:store_staff, [:store_id])

    drop_if_exists index(:store_staff, [:user_id])

    alter table(:store_staff, prefix: prefix()) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "store_staff_user_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :store_id,
             references(:stores,
               column: :id,
               name: "store_staff_store_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    drop constraint(:tags, "tags_store_id_fkey")

    drop_if_exists unique_index(:tags, [:store_id, :slug], name: "tags_unique_slug_index")

    drop table(:tags, prefix: prefix())

    alter table(:variants, prefix: prefix()) do
      remove :position
      remove :low_stock_threshold
      remove :reserved_quantity
      remove :barcode
      remove :cost_price
    end
  end
end
