defmodule Algoie.Repo.TenantMigrations.AddProductCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:product_categories, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :product_id,
          references(:products,
            column: :id,
            name: "product_categories_product_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :category_id,
          references(:categories,
            column: :id,
            name: "product_categories_category_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:product_categories, [:product_id, :category_id],
             name: "product_categories_unique_product_category_index"
           )
  end

  def down do
    drop constraint(:product_categories, "product_categories_product_id_fkey")

    drop constraint(:product_categories, "product_categories_category_id_fkey")

    drop_if_exists unique_index(:product_categories, [:product_id, :category_id],
                     name: "product_categories_unique_product_category_index"
                   )

    drop table(:product_categories, prefix: prefix())
  end
end
