defmodule Algoie.Repo.TenantMigrations.AddMediaFolders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:media_folders, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :store_id,
          references(:stores,
            column: :id,
            name: "media_folders_store_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :name, :text, null: false

      add :parent_id,
          references(:media_folders,
            column: :id,
            name: "media_folders_parent_id_fkey",
            type: :uuid,
            prefix: prefix()
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:media_assets, prefix: prefix()) do
      add :folder_id,
          references(:media_folders,
            column: :id,
            name: "media_assets_folder_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end
  end

  def down do
    drop constraint(:media_assets, "media_assets_folder_id_fkey")

    alter table(:media_assets, prefix: prefix()) do
      remove :folder_id
    end

    drop constraint(:media_folders, "media_folders_store_id_fkey")

    drop constraint(:media_folders, "media_folders_parent_id_fkey")

    drop table(:media_folders, prefix: prefix())
  end
end
