defmodule Algoie.Repo.Migrations.Day2Commerce do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:store_registry, prefix: "public") do
      modify :tenant_id, :text
    end
  end

  def down do
    alter table(:store_registry, prefix: "public") do
      modify :tenant_id, :uuid
    end
  end
end
