defmodule Algoie.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    execute("CREATE SCHEMA IF NOT EXISTS public")

    create table(:tenants, primary_key: false, prefix: "public") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :owner_email, :citext, null: false
      add :billing_status, :text, null: false, default: "trial"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tenants, [:owner_email],
             name: "tenants_unique_owner_email_index",
             prefix: "public"
           )

    execute("CREATE SCHEMA IF NOT EXISTS public")

    create table(:store_registry, primary_key: false, prefix: "public") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :tenant_id, :text, null: false
      add :store_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:store_registry, [:slug],
             name: "store_registry_unique_slug_index",
             prefix: "public"
           )
  end

  def down do
    drop_if_exists unique_index(:store_registry, [:slug],
                     name: "store_registry_unique_slug_index",
                     prefix: "public"
                   )

    drop table(:store_registry, prefix: "public")

    drop_if_exists unique_index(:tenants, [:owner_email],
                     name: "tenants_unique_owner_email_index",
                     prefix: "public"
                   )

    drop table(:tenants, prefix: "public")

    drop table(:tokens)
  end
end
